# Default values for marketsummary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: marketsummary:latest
version: "0.0.1-SNAPSHOT" 
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
workload: springtrader

service:
  type: ClusterIP
  port: 8080

canary:
  enabled: false

istioDomain: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: "512Mi"
    cpu: "128m"
  limits:
    memory: "768Mi"
    cpu: "512m"

nodeSelector: {}

tolerations: []

affinity: {}
