{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Values.version }}
spec:
  provider: istio
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: {{ .Values.canary.progressDeadlineSeconds }}
  {{- if .Values.hpa.enabled }}
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: {{ .Chart.Name }}
  {{- end }}
  service:
    # container port
    port: {{ .Values.service.port }}
    {{- if .Values.canary.istioIngress.enabled }}
    gateways:
      - istio-system/app-gateway
    hosts:
      - springtrader-{{ .Values.productName }}.{{ .Values.istioDomain }}
    {{- end }}
    # Istio traffic policy (optional)
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE
    # HTTP match conditions (optional)
    match:
      - uri:
          prefix: /spring-nanotrader-services/api/marketSummary
    # HTTP rewrite (optional)
    rewrite:
      uri: /marketsummary
    # HTTP timeout (optional)
    timeout: 30s
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  canaryAnalysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 1m
    {{- if .Values.canary.loadtest.enabled }}
    webhooks:
      - name: load-test-get
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 http://{{ .Chart.Name }}:{{ .Values.service.port }}"
      - name: load-test-post
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 -m POST -d '{\"test\": true}' http://{{ .Chart.Name }}:{{ .Values.service.port }}/echo"
    {{- end }}
{{- end }}
